services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:v1
    container_name: backend
    volumes:
      - ./tests:/var/www/tests
    depends_on:
      - database
    # ports:
    #   - "9000:9000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:v1
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3002:80"
    networks:
      - app-network

  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_DATABASE: brand
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge